//
// CharactersAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public class CharactersAPI {

    public init() {}
    public func printService() {
        print("🥺🥺🥺🥺🥺🥺🥺🥺")
    }
    /**
     get all characters
     
     - parameter page: (query)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func getAllCharacters(page: Int, apiResponseQueue: DispatchQueue = OpenAPIClientAPI.apiResponseQueue, completion: @escaping ((_ data: [Description]?, _ error: Error?) -> Void)) -> RequestTask {
        return getAllCharactersWithRequestBuilder(page: page).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     get all characters
     - GET /characters
     - Get All Characters
     - parameter page: (query)  
     - returns: RequestBuilder<[Description]> 
     */
    open class func getAllCharactersWithRequestBuilder(page: Int) -> RequestBuilder<[Description]> {
        let localVariablePath = "/characters"
        let localVariableURLString = OpenAPIClientAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "page": page,
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[Description]>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()
        print("🥺getAllCharactersWithRequestBuilder service is done!🤩")

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters)
    
    }
}
